version: '3.7'
networks:
  awari-pipelines:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "172.18.0.0/16"
                gateway: "172.18.0.1"

# Settings dna configuration for apache-airflow
x-awari-airflow-common: &awari-airflow-common
  build: 
    dockerfile: ../data/airflow/Dockerfile
  user: "${AIRFLOW_UID}:0"
  env_file: 
    - ../data/airflow/.env
  volumes:
    - ../data/airflow/dags:/opt/airflow/dags
    - ../data/airflow/logs:/opt/airflow/logs
    - ../data/airflow/downloads:/opt/airflow/downloads
    - ../data/airflow/plugins:/opt/airflow/plugins
    - /var/run/docker.sock:/var/run/docker.sock

x-awari-airflow-depends-on: &awari-airflow-depends-on
  depends_on:
    awari-airflow-postgres:
      condition: service_healthy
    awari-airflow-init:
      condition: service_completed_successfully

services:
  # Airflow Services
  awari-airflow-postgres:
    image: postgres:latest
    container_name: awari-airflow-postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    env_file:
      - ../data/airflow/.env
    volumes:
      - ../data/airflow/postgres-data:/var/lib/postgresql/data
    networks:
      awari-pipelines:
        ipv4_address: 172.18.0.110

  awari-airflow-scheduler:
    <<: *awari-airflow-common
    <<: *awari-airflow-depends-on
    container_name: awari-airflow-scheduler
    command: scheduler
    restart: on-failure
    ports:
      - "8793:8793"
    networks:
      awari-pipelines:
        ipv4_address: 172.18.0.111

  awari-airflow-webserver:
    <<: *awari-airflow-common
    <<: *awari-airflow-depends-on
    container_name: awari-airflow-webserver
    restart: always
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
    networks:
        awari-pipelines:
          ipv4_address: 172.18.0.112
  
  awari-airflow-init:
    <<: *awari-airflow-common
    container_name: awari-airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins /sources/downloads
        chmod 777 -R /sources/downloads
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins,downloads}
        exec /entrypoint airflow version
    networks:
      - awari-pipelines